server:
  port: 9009
  servlet:
    session:
      timeout: 7200
    multipart:
      max-file-size: 5MB
sys:
  config:
    vipSeasonPrice: 99
    vipSeasonText: 夕觉素材季卡VIP
    vipYearPrice: 198
    vipYearText: 夕觉素材年卡VIP
    vipLifePrice: 299
    vipLifeText: 夕觉素材终身VIP
    #点击跳转到某一个分类，填/source/toCategory?categoryId=1
    #点击跳转到具体某一个素材，填/source/toDetail?id=1
    #首页主题轮播图
    mainLoop1: /source/toCategory?categoryId=1
    mainLoop2: /source/toCategory?categoryId=2
    mainLoop3: /source/toCategory?categoryId=3
    mainLoop4: /source/toCategory?categoryId=4
    mainLoop5: /source/toCategory?categoryId=5
    #轮播图下发4个图
    mainBottom1: /source/toCategory?categoryId=1
    mainBottom2: /source/toCategory?categoryId=2
    mainBottom3: /source/toCategory?categoryId=3
    mainBottom4: /source/toCategory?categoryId=4
    #登录下方1个图
    loginBottom: /source/toDetail?id=1
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat #监控统计拦截的filters
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/xijuesucai2?useAffectedRows=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      #password: an80238023
      password: qun9420
      initial-size: 1 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 5 #最小连接池数量
      max-active: 50 #最大连接池数量
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降
      time-between-eviction-runs-millis: 60000 #间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 'x' #用来检测连接是否有效的sql，要求是一个查询语句。
      test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-pool-prepared-statement-per-connection-size: 20
  main:
    # Spring Boot 2.1 需要显式开启bean override
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
    view:
      prefix: /
      suffix: .html
    thymeleaf:
      cache: false
  resources:
    chain:
      cache: true
      compressed: true
    cache:
      period: 3600
  devtools:
    restart:
      enabled: true
      additional-pahts: src/main/java
      exclude: WEB-INF/**
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台打印sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/*Mapper.xml

# PageHelper分页插件配置
pagehelper:
  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
  helper-dialect: mysql
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum。
  params: count=countSql


##支付配置
pay:
  #支付宝支付
  alipay:
    #支付宝gatewayUrl
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    #商户应用id
    appid: 2016102200739243
    #应用RSA私钥，用于对商户请求报文加签
    app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNfBeFU9yCZ9fn8F9vY7jzXMiwKkFhJZdQMbSnBjfS3tvpt0sPD/1r4F4Vb/vt4Ou4CHZwlYgF689yfE7EffX0xrgZxMeszr2W/DO7B7it4OumjKGte/1ea855uVc/1Ey3TLnu9t+VDR49aGM2++IqWqiuB2Pe9IkM9GQL15wkkGf+aaCniOHOl9ncwBFiqqNcQAujcR96KrSsBwyoHPwxcgQC1br3ekSwb55N1txvDCQ20gy0eXnOZ//n8E0GA2ixSJ/68lUgV6nJACHhC6pz3/zwETgG7kYtYGayDbf2FEOYvzD7b0tBmVYuMokLDWQ8mpwzTfWxrHlhXzzSYOOhAgMBAAECggEACjsV7FMzF87wgtoT3JcmcZqc/HghwCeauHbPrGA7uyjYWB8j81PhrGJOC1jMq9fe07Dw95Uof90cZBfvDjBZj7iq6VocYjeU6A0WpIibZx9jiuiSbFwR5zj+djjbwUbVwU9wBoKdikankCMzQW+XXB6wId1w8FdYbbJiZaTSqqYW3F5wTqjqClFqE9WP1/QJPagBzz0/RAj0ttijB3T/vwpUUpDG8w535xFORpjuWcspX9/Cp5bNO9JCvQORwbe9uyMdCmspQvcx4iFNHbnfu6nPgFgregLX30pnfmtErUsC1CK0z+m66tKLWldHCIyNp9YJ8qWLHacfVfSwkgUrAQKBgQDU8OyEerNTY0bH9GVrp7B0HTKtJoGlbg+U62TDn5pOpBTGytPLOHvDGl3Rr0QXZQovSwUTXQ77Qw6/XLELL6RFO03Pb+3atA59rOZjahpwLNt5/EhvWO6/OcO4urseeXqTkHFmwIMzCvMFwo++q9FBlCHGqoimoMPdAMiG/nn+UQKBgQCqGCsgHP6S1hbehXaX0ce4NATPDVPRfXtK+qHcH8qfEqCHO0whxwVCyUTiLbb3PQdZgQzZ1DsuuS9NcJlEQLW1RFgLEmFbB9aauY70KKsH9LdO7D1CpY3EhujASdLkOEg4GbkvKOeDFsDGPnD2ySLX0dBNzKWqgtLXarBlMRmsUQKBgFGvKcuYFfpC9v/1LIKjjPi9ypbJUqpXEfsaYUj5jIPmRWIMpDosrK0nDB5HkWM4CzQhHw1SgVC5ZIrbz75uxCEaorqUQTXIJFbpYGd6aDHnwzmEIXU1NEB+tCnE18rU5sR8gEPeTXXjGV54SBPobRku7dX7zPe+a+P3TPUb4UhBAoGAKkQZK0CpLZmPUzn8zxrssuQSMdUQ9+RjZ61B3S31LnP1ecUNVPNcZk0XFdDgPy1mDyKXK+Wl0yVnEKojG6esv189NXsawAEBna7wS9FzNmXjyvO/ATmcMbKIUYfGpLkrkO0rbAGRDazwuBI6BcjTJKfZSAvLOsSJWcgEDxEVXRECgYEAhGzCL1Zx4dy15wKFfTzbEJEpXlp7pLmSuFc01AVpT4cr8gT26JUwuz3Cjdy2RApl4aSbVivKBLtu3y+29/mDFOyGwSRRGGPQSqGdV3VgbrIelmNbb3rckhCVyHcMQfy/PL1GIk4D8V6KlHX+jqzvkIe8cTeFrrs7Ju9pR3Li76I=
    #支付宝RSA公钥，用于验签支付宝应答
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArBUpehi/lD+vTlwx4E8zFohxooLrBlzCKOTQK3FJLOxsMgPA+pCMPNR7qlC3Y/h54IDyKmTlwagk4p3Q6pEqEDwIs8NgPg3vqrLvxD3TxOYiuHr+EJvfZmhN4uYAiI4Q7U9N7dhSKRIE9PMf28Z9qBTkAis+hW6SneMjDfSPJBJTT9CwHnRcrsGxwCmPTYwaGqFjj2Xw4SkcNoXdqE39aYqzBMJI1+GBIe62u+5OXUblRsZjbalJw9+zF3Ysu6rx+NfAkCidQzphS0k0xLGQrJUSAUyEe44VLYa4T8BCVuREFyqxwRNkyBbkxTfUqyhA65U91JFjaI6rinzrjODCgQIDAQAB
    #支付成功的异步通知回调接口
    notify-url: http://111.229.77.76:9009//alipay/notify
    return-url: http://111.229.77.76:9009//alipay/return
  #微信app支付
  wxpay:
    #你的appid
    appID: wx382210032fea2a09
    #你的商户id
    mchID: 1302524401
    #你的api秘钥，不是appSecret
    key: a403e7605a7b00b3e6bf7ee94e0b4cfe
    #从微信商户平台下载的安全证书存放的路径、我放在resources下面,切记一定要看看target目录下的class文件下有没有打包apiclient_cert.p12文件
    #static/cert/wxpay/apiclient_cert.p12
    certPath:
    #微信支付成功的异步通知接口
    payNotifyUrl: http://111.229.77.76:9009/wxPay/notify
logging:
  file:
    path: c:\xijuesucai\logs